name: "auto-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential cmake automake libtool autoconf
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/scripts
          ./build_deps.sh && cd ../build
          cmake .. -DXMRIG_DEPS=scripts/deps
          make -j$(nproc)
          echo "done!"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            xmrig/build/xmrig
            
